# Site settings
title: Kein blog
description: Kein subtle blog
email: kein.you@gmail.com
baseurl: ""
url: ""
#favicon
favicon: /favicon.png

#feed
feedburner_username: ""
#twitter
twitter_username: drkein
github_username:  drkein

#linkedin
linkedin_username: 

#google analytics
google_analytics_id : 
#gplus
gplus_username: 

#fb_username
fb_username: 

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: drkein
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  pranavrajs:
    display_name: DrKein
    email: kein.you@gmail.com
    fb: 
    linkedin: 
    twitter: drkein
    github: drkein
